apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: devops-project
        image: rehan568388/python-docker-image:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "devops-project-service"
  namespace: "devops-project"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "project"
  type: "LoadBalancer"






